Repository sgdevcamp2025/kickzo, pull requests merged in 2025-01, with the labels that each got.

#5 [COMMON] FEAT: infra 개발 환경을 위한 도커 환경 세팅 #4
  src/README.md
  src/backend/chat-service/.dockerignore
  src/backend/chat-service/.gitignore
  src/backend/chat-service/Dockerfile
  src/backend/chat-service/package-lock.json
  src/backend/chat-service/package.json
  src/backend/chat-service/src/chat-server.js
  src/infra/README.md
  src/infra/docker-compose.yml
  src/makefile
Labels: FEAT, DOCS

#9 [COMMON] FIX: makefile 수정 및 Chat README 작성 #6
  src/backend/chat-service/README.md
  src/makefile
Labels: FIX, DOCS

#12 [iOS] FEAT: iOS 프로젝트 초기 설정 #11
  .gitignore
  src/iOS/KickTube/.gitignore
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/App/AppDelegate.swift
  src/iOS/KickTube/KickTube/App/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  src/iOS/KickTube/KickTube/App/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/iOS/KickTube/KickTube/App/Resource/Assets.xcassets/Contents.json
  src/iOS/KickTube/KickTube/App/Resource/Base.lproj/LaunchScreen.storyboard
  src/iOS/KickTube/KickTube/App/Resource/Info.plist
  src/iOS/KickTube/KickTube/App/SceneDelegate.swift
  src/iOS/KickTube/KickTube/Features/ViewController.swift
  src/iOS/KickTube/KickTube/KickTubeTests/KickTubeTests.swift
  src/iOS/KickTube/KickTube/KickTubeUITests/KickTubeUITests.swift
  src/iOS/KickTube/KickTube/KickTubeUITests/KickTubeUITestsLaunchTests.swift
Labels: FEAT

#10 [FE] FEAT: fe - 개발환경 세팅 #8
  src/frontend/.gitignore
  src/frontend/.storybook/main.ts
  src/frontend/.storybook/preview.ts
  src/frontend/README.md
  src/frontend/eslint.config.js
  src/frontend/index.html
  src/frontend/package.json
  src/frontend/pnpm-lock.yaml
  src/frontend/prettier.config.mjs
  src/frontend/src/App.css
  src/frontend/src/App.tsx
  src/frontend/src/index.css
  src/frontend/src/main.tsx
  src/frontend/src/stories/Button.stories.ts
  src/frontend/src/stories/Button.tsx
  src/frontend/src/stories/Configure.mdx
  src/frontend/src/stories/Header.stories.ts
  src/frontend/src/stories/Header.tsx
  src/frontend/src/stories/Page.stories.ts
  src/frontend/src/stories/Page.tsx
  src/frontend/src/stories/assets/accessibility.png
  src/frontend/src/stories/assets/accessibility.svg
  src/frontend/src/stories/assets/addon-library.png
  src/frontend/src/stories/assets/assets.png
  src/frontend/src/stories/assets/avif-test-image.avif
  src/frontend/src/stories/assets/context.png
  src/frontend/src/stories/assets/discord.svg
  src/frontend/src/stories/assets/docs.png
  src/frontend/src/stories/assets/figma-plugin.png
  src/frontend/src/stories/assets/github.svg
  src/frontend/src/stories/assets/share.png
  src/frontend/src/stories/assets/styling.png
  src/frontend/src/stories/assets/testing.png
  src/frontend/src/stories/assets/theming.png
  src/frontend/src/stories/assets/tutorials.svg
  src/frontend/src/stories/assets/youtube.svg
  src/frontend/src/stories/button.css
  src/frontend/src/stories/header.css
  src/frontend/src/stories/page.css
  src/frontend/src/vite-env.d.ts
  src/frontend/tsconfig.app.json
  src/frontend/tsconfig.json
  src/frontend/tsconfig.node.json
  src/frontend/vite.config.ts
Labels: FEAT

#14 [COMMON] FIX: kong manager oss 추가 #13
  src/infra/.env
  src/infra/docker-compose.yml
  src/infra/kong/Dockerfile
Labels: FIX

#16 [iOS] FEAT: 네트워크 계층 개발 #15
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Enum/HTTPMethod.swift
  src/iOS/KickTube/KickTube/Common/Enum/NetworkError.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/DefaultEndPoint.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/JSONDecodeService.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/NetworkManager.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/EndPointConfigurable.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/URLRequestBuildable.swift
  src/iOS/KickTube/KickTube/Info.plist
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/Contents.json
  src/iOS/KickTube/KickTube/Resource/Base.lproj/LaunchScreen.storyboard
Labels: FEAT

#25 [iOS] FEAT: 매크로를 사용한 데이터 모델 변환 및 가공 #17
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/App/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  src/iOS/KickTube/KickTube/App/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/iOS/KickTube/KickTube/App/Resource/Assets.xcassets/Contents.json
  src/iOS/KickTube/KickTube/App/Resource/Base.lproj/LaunchScreen.storyboard
  src/iOS/KickTube/KickTube/App/Resource/Info.plist
  src/iOS/ManipulateDataModel/.gitignore
  src/iOS/ManipulateDataModel/Package.resolved
  src/iOS/ManipulateDataModel/Package.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModel/ManipulateDataModel.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelClient/main.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/DTOMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/DataModelMappingMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/KeyMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/ManipulateDataModelMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/ManipulateDataModelPlugin.swift
  src/iOS/ManipulateDataModel/Tests/ManipulateDataModelTests/ManipulateDataModelTests.swift
Labels: FEAT, TEST, iOS

#24 [COMMON] DOCS: 리드미 컨벤션 추가 및 템플릿 수정 #22
  .github/ISSUE_TEMPLATE/bug_issue.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: DOCS

#19 [FE] FEAT: 공통 Input 컴포넌트 만들기 및 storybook 작성 #18
  src/frontend/src/assets/img/Add.svg
  src/frontend/src/assets/img/Check.svg
  src/frontend/src/assets/img/MicrophoneOn.svg
  src/frontend/src/components/common/button/index.css.ts
  src/frontend/src/components/common/button/index.tsx
  src/frontend/src/components/common/input/Input.tsx
  src/frontend/src/components/common/input/index.css.ts
  src/frontend/src/index.css
  src/frontend/src/stories/Button.stories.ts
  src/frontend/src/stories/Button.stories.tsx
  src/frontend/src/stories/Input.stories.ts
Labels: FEAT, frontend

#21 [BE] FEAT: Database 추가 & docker 환경 구축 #20
  src/backend/mysql_db/Dockerfile
  src/backend/mysql_db/cleanup.sh
  src/backend/mysql_db/docker-compose.yml
  src/backend/mysql_db/init.sql
Labels: FEAT, backend

#40 [BE] FEAT: 메인 서버 Entity 세팅 #31
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kickzo.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/.idea/.gitignore
  src/.idea/checkstyle-idea.xml
  src/.idea/inspectionProfiles/Project_Default.xml
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/src.iml
  src/.idea/vcs.xml
  src/backend/main-server/main/.gitattributes
  src/backend/main-server/main/.gitignore
  src/backend/main-server/main/build.gradle
  src/backend/main-server/main/gradle/wrapper/gradle-wrapper.jar
  src/backend/main-server/main/gradle/wrapper/gradle-wrapper.properties
  src/backend/main-server/main/gradlew
  src/backend/main-server/main/gradlew.bat
  src/backend/main-server/main/settings.gradle
  src/backend/main-server/main/src/main/java/com/kickzo/main/MainApplication.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/Playlist.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/Room.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/RoomUser.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/RoomUserId.java
  src/backend/main-server/main/src/main/resources/application.properties
  src/backend/main-server/main/src/test/java/com/kickzo/main/MainApplicationTests.java
  src/package-lock.json
Labels: FEAT, ETC, 🕹️BE

#42 Main to Dev
  src/backend/mysql_db/Dockerfile
  src/backend/mysql_db/cleanup.sh
  src/backend/mysql_db/docker-compose.yml
  src/backend/mysql_db/init.sql
Labels: ETC

#34 [iOS] FEAT: View 기본 세팅 #27
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/App/SceneDelegate.swift
  src/iOS/KickTube/KickTube/Common/Base/BaseReactor.swift
  src/iOS/KickTube/KickTube/Common/Base/BaseViewController.swift
  src/iOS/KickTube/KickTube/Common/Enum/ComponentSize.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UIImage+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UIViewController+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Then.swift
  src/iOS/KickTube/KickTube/Features/TabBar/TabBarViewController.swift
  src/iOS/KickTube/KickTube/Features/ViewController.swift
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/create.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/create.imageset/create.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/friend.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/friend.imageset/friend.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/home.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/home.imageset/home.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/notification.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/notification.imageset/notification.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/playlist.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/playlist.imageset/playlist.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/primary.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/profile.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/profile.imageset/profile.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/search.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/search.imageset/search.svg
Labels: FEAT, 📱iOS

#30 [FE] FEAT: Sidebar UI #26
  src/frontend/src/App.tsx
  src/frontend/src/assets/data/chatDataTest.ts
  src/frontend/src/assets/data/memberListTest.ts
  src/frontend/src/assets/img/AddUser.svg
  src/frontend/src/assets/img/HeadphoneOffRed.svg
  src/frontend/src/assets/img/HeadphoneOn.svg
  src/frontend/src/assets/img/Me.svg
  src/frontend/src/assets/img/MicrophoneOffRed.svg
  src/frontend/src/assets/img/ProfileImg.svg
  src/frontend/src/assets/img/RoleManager.svg
  src/frontend/src/assets/img/RoleOwner.svg
  src/frontend/src/assets/img/SidebarChat.svg
  src/frontend/src/assets/img/SidebarMember.svg
  src/frontend/src/assets/img/SidebarPlaylist.svg
  src/frontend/src/assets/img/SidebarVoicechat.svg
  src/frontend/src/assets/img/Trashcan.svg
  src/frontend/src/components/common/button/index.css.ts
  src/frontend/src/components/common/button/index.tsx
  src/frontend/src/components/common/input/index.css.ts
  src/frontend/src/components/common/input/index.tsx
  src/frontend/src/components/common/rolenickname/index.css.ts
  src/frontend/src/components/common/rolenickname/index.tsx
  src/frontend/src/components/common/smallprofile/index.css.ts
  src/frontend/src/components/common/smallprofile/index.tsx
  src/frontend/src/components/sidebar/chat/chatNickname.tsx
  src/frontend/src/components/sidebar/chat/index.css.ts
  src/frontend/src/components/sidebar/chat/index.tsx
  src/frontend/src/components/sidebar/index.css.ts
  src/frontend/src/components/sidebar/index.tsx
  src/frontend/src/components/sidebar/memberList/index.css.ts
  src/frontend/src/components/sidebar/memberList/index.tsx
  src/frontend/src/components/sidebar/playlist/index.css.ts
  src/frontend/src/components/sidebar/playlist/index.tsx
  src/frontend/src/components/youtubePlayer/index.tsx
  src/frontend/src/index.css
  src/frontend/src/pages/room/index.tsx
  src/frontend/src/stories/Button.stories.tsx
  src/frontend/src/stories/Input.stories.ts
  src/frontend/src/types/enums/ButtonColor.ts
  src/frontend/src/types/enums/InputDesign.ts
  src/frontend/src/types/enums/ProfileType.ts
  src/frontend/src/types/enums/SidebarType.ts
  src/frontend/src/types/enums/UserRole.ts
  src/frontend/tsconfig.app.json
  src/frontend/vite.config.ts
Labels: FEAT, 🖥️FE

#49 [BE] FEAT: 메인서버 메인페이지 개발 #41
  src/backend/main-server/main/build.gradle
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/CreateRoomRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/RoomResponseDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/Room.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/RoomUser.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/RoomUserId.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/PlaylistRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomUserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/MainPageService.java
Labels: FEAT, 🕹️BE

#50 [iOS] FEAT: 로그인 뷰 구현 #37
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Base/BaseReactor.swift
  src/iOS/KickTube/KickTube/Common/Base/BaseViewController.swift
  src/iOS/KickTube/KickTube/Common/Components/BlackTextButton.swift
  src/iOS/KickTube/KickTube/Common/Components/CheckBoxView.swift
  src/iOS/KickTube/KickTube/Common/Components/DivideLineView.swift
  src/iOS/KickTube/KickTube/Common/Components/LightStrokeTextField.swift
  src/iOS/KickTube/KickTube/Common/Components/RoundButton.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginDataModel.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginReactor.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginViewController.swift
  src/iOS/KickTube/KickTube/Features/TabBar/TabBarViewController.swift
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/kLightgary.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/logo.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/logo.imageset/logo.svg
  src/iOS/KickTube/KickTube/Resource/KFont.swift
Labels: FEAT, 📱iOS

#44 [BE] FEAT: kafka docker container 추가 #43
  src/backend/kafka_docker/cleanup.sh
  src/backend/kafka_docker/docker-compose-kafkaui.yml
  src/backend/kafka_docker/docker-compose.yml
Labels: FEAT, 🕹️BE

#51 [FE] FEAT: layout 및 router 설정 #39
  .gitignore
  src/frontend/index.html
  src/frontend/package.json
  src/frontend/pnpm-lock.yaml
  src/frontend/src/App.css
  src/frontend/src/App.tsx
  src/frontend/src/assets/img/AddCircle.svg
  src/frontend/src/assets/img/Bell.svg
  src/frontend/src/assets/img/HomeLine.svg
  src/frontend/src/assets/img/Logo.png
  src/frontend/src/assets/img/PlaylistFill.svg
  src/frontend/src/assets/img/PlaylistLine.svg
  src/frontend/src/assets/img/UsersFill.svg
  src/frontend/src/assets/img/UsersLine.svg
  src/frontend/src/assets/img/homeFill.svg
  src/frontend/src/components/LeftNavBar/index.css.ts
  src/frontend/src/components/LeftNavBar/index.tsx
  src/frontend/src/components/TopNavBar/index.css.ts
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/index.css
  src/frontend/src/pages/FriendPage/index.tsx
  src/frontend/src/pages/HomePage/index.tsx
  src/frontend/src/pages/Layout/index.css.ts
  src/frontend/src/pages/Layout/index.tsx
  src/frontend/src/pages/LoginPage/index.tsx
  src/frontend/src/pages/MyRoomPage/index.tsx
  src/frontend/src/pages/NotFoundPage/index.tsx
  src/frontend/src/pages/RegisterPage/index.tsx
  src/frontend/src/pages/SettingPage/index.tsx
Labels: FEAT, 🖥️FE

#54 [FE] FEAT: 로그인, 회원가입, 비밀번호 재설정 UI 추가 #53
  src/frontend/.gitignore
  src/frontend/.prettierignore
  src/frontend/src/App.css
  src/frontend/src/App.tsx
  src/frontend/src/assets/img/Logo.png
  src/frontend/src/assets/img/Logo.svg
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/components/common/LogoButton/index.tsx
  src/frontend/src/components/common/button/index.css.ts
  src/frontend/src/main.tsx
  src/frontend/src/pages/LoginPage/index.css.ts
  src/frontend/src/pages/LoginPage/index.tsx
  src/frontend/src/pages/PasswordResetPage/index.css.ts
  src/frontend/src/pages/PasswordResetPage/index.tsx
  src/frontend/src/pages/RegisterPage/index.css.ts
  src/frontend/src/pages/RegisterPage/index.tsx
  src/frontend/tsconfig.app.json
Labels: FEAT, 🖥️FE

#46 [FE] FEAT: 클릭시 나타나는 프로필 UI #45
  src/frontend/src/components/common/bigProfile/index.css.ts
  src/frontend/src/components/common/bigProfile/index.tsx
  src/frontend/src/components/common/button/index.css.ts
  src/frontend/src/components/common/button/index.tsx
  src/frontend/src/components/iconButton/index.css.ts
  src/frontend/src/components/iconButton/index.tsx
  src/frontend/src/components/roleChangeButton/index.css.ts
  src/frontend/src/components/roleChangeButton/index.tsx
  src/frontend/src/components/sidebar/index.tsx
Labels: FEAT, 🖥️FE

#65 [INFRA] FEAT: frontend CI 추가 #64
  .github/workflows/frontend-ci.yaml
  src/frontend/package.json
  src/frontend/pnpm-lock.yaml
Labels: FEAT, infra

#66 [FE] FIX: ci 경로 수정 #64
  .github/workflows/frontend-ci.yaml
Labels: FIX, infra

#63 [BE] FIX: change MongoDB version #62
  src/backend/mongo_db/docker-compose.yml
Labels: FIX, 🕹️BE

#73 [INFRA] FEAT: root에 docker-compose로 통합 빌드 #72
  src/.env
  src/backend/chat-server/docker-compose.yml
  src/backend/chat-server/src/main/resources/application.properties
  src/backend/chat-service/.dockerignore
  src/backend/chat-service/.gitignore
  src/backend/chat-service/Dockerfile
  src/backend/chat-service/README.md
  src/backend/chat-service/package-lock.json
  src/backend/chat-service/package.json
  src/backend/chat-service/src/chat-server.js
  src/backend/kafka/cleanup.sh
  src/backend/kafka/docker-compose-kafkaui.yml
  src/backend/kafka/docker-compose.yml
  src/backend/mongo-db/.gitignore
  src/backend/mongo-db/cleanup.sh
  src/backend/mongo-db/docker-compose.yml
  src/backend/mongo-db/mongo-init.js
  src/backend/mongo_db/docker-compose.yml
  src/backend/mysql-db/.gitignore
  src/backend/mysql-db/Dockerfile
  src/backend/mysql-db/cleanup.sh
  src/backend/mysql-db/docker-compose.yml
  src/backend/mysql-db/init.sql
  src/backend/mysql_db/docker-compose.yml
  src/docker-compose.yml
  src/infra/.env
  src/infra/docker-compose.yml
  src/infra/kong/kong.yml
  src/makefile
Labels: FEAT, infra
