Repository sgdevcamp2025/kickzo, pull requests merged in 2025-02, with the labels that each got.

#67 [iOS] FEAT: 홈(메인) 화면 구현 #36
  src/iOS/KickTube/KickTube/Common/Enum/ComponentSize.swift
  src/iOS/KickTube/KickTube/Common/Extensions/String+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UICollectionView+Extnesions.swift
  src/iOS/KickTube/KickTube/Common/Utilities/CacheManager.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/YoutubeEndPoint.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/NetworkManager.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Router/YoutubeRouter.swift
  src/iOS/KickTube/KickTube/Common/Utilities/ReuseIdentifiable.swift
  src/iOS/KickTube/KickTube/Features/Home/HomeDataModel.swift
  src/iOS/KickTube/KickTube/Features/Home/HomeReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/HomeVideoCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/HomeViewController.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginViewController.swift
  src/iOS/KickTube/KickTube/Features/TabBar/TabBarViewController.swift
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/defaultProfile.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/defaultProfile.imageset/defaultProfile.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/kGray.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/logoSmall.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/logoSmall.imageset/logoSmall.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/videoThumbnail.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/videoThumbnail.imageset/videoThumbnail.svg
Labels: FEAT, 📱iOS

#77 [iOS] 방 생성 모달 및 Alert 모달 구현 #68
  src/iOS/KickTube/KickTube/App/SceneDelegate.swift
  src/iOS/KickTube/KickTube/Common/Components/CheckBoxView.swift
  src/iOS/KickTube/KickTube/Common/Components/LightStrokeTextField.swift
  src/iOS/KickTube/KickTube/Common/Components/LightStrokeTextView.swift
  src/iOS/KickTube/KickTube/Common/Components/RoundButton.swift
  src/iOS/KickTube/KickTube/Common/Enum/AlertMessage.swift
  src/iOS/KickTube/KickTube/Common/Enum/ComponentSize.swift
  src/iOS/KickTube/KickTube/Common/Extensions/String+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UICollectionView+Extenions.swift
  src/iOS/KickTube/KickTube/Common/View/AlertViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/HomeDataModel.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/CreateRoomReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/HomeReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/HomeVideoCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/CreateRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/HomeViewController.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginViewController.swift
  src/iOS/KickTube/KickTube/Features/TabBar/TabBarViewController.swift
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/create.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/disableEye.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/disableEye.imageset/disableEye.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/friend.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/kDarkgray.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/kLightgray1.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/kLightgray2.colorset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/play.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/play.imageset/play.svg
Labels: FEAT, 📱iOS

#84 [FE] FEAT: Home UI 추가 #83
  src/frontend/.gitignore
  src/frontend/src/App.css
  src/frontend/src/App.tsx
  src/frontend/src/assets/data/videoListTest.ts
  src/frontend/src/components/VideoCard/index.css.ts
  src/frontend/src/components/VideoCard/index.tsx
  src/frontend/src/pages/HomePage/index.css.ts
  src/frontend/src/pages/HomePage/index.tsx
  src/frontend/src/pages/Layout/index.css.ts
  src/frontend/src/pages/Layout/index.tsx
  src/frontend/src/types/dto/VideoCard.dto.ts
Labels: FEAT, 🖥️FE

#82 [BE] FEAT: 방 입장 로직 구현
  src/.idea/.gitignore
  src/.idea/checkstyle-idea.xml
  src/.idea/inspectionProfiles/Project_Default.xml
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/src.iml
  src/.idea/vcs.xml
  src/backend/main-server/main/build.gradle
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/PlaylistDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/RoomDetailsDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/RoomEntryResponseDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/RoomInfoDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/RoomRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/UserListDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/Room.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/PlaylistRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomUserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/UserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
Labels: FEAT, 🕹️BE

#70 [FE] FEAT: Playlist Item 구현 #61
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.css.ts
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.tsx
  src/frontend/src/components/Sidebar/Playlist/index.css.ts
  src/frontend/src/components/Sidebar/Playlist/index.tsx
  src/frontend/src/components/Sidebar/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
  src/frontend/src/pages/RoomPage/index.tsx
  src/frontend/src/stores/useVideoStore.ts
Labels: FEAT, 🖥️FE

#76 [BE] FEAT: 인증, 유저 서버 초기 구현 #29
  src/.env
  src/backend/auth-server/.gitignore
  src/backend/auth-server/.prettierrc
  src/backend/auth-server/Dockerfile
  src/backend/auth-server/README.md
  src/backend/auth-server/docker-compose.yml
  src/backend/auth-server/eslint.config.mjs
  src/backend/auth-server/nest-cli.json
  src/backend/auth-server/package.json
  src/backend/auth-server/pnpm-lock.yaml
  src/backend/auth-server/src/app.module.ts
  src/backend/auth-server/src/auth/auth.controller.ts
  src/backend/auth-server/src/auth/auth.module.ts
  src/backend/auth-server/src/auth/auth.service.ts
  src/backend/auth-server/src/auth/decorator/authorization.decorator.ts
  src/backend/auth-server/src/auth/dto/parse-bearer-token.dto.ts
  src/backend/auth-server/src/auth/dto/user-login.dto.ts
  src/backend/auth-server/src/auth/dto/user.dto.ts
  src/backend/auth-server/src/auth/interface/token-payload.interface.ts
  src/backend/auth-server/src/main.ts
  src/backend/auth-server/tsconfig.build.json
  src/backend/auth-server/tsconfig.json
  src/backend/mysql-db/Dockerfile
  src/backend/mysql-db/docker-compose.yml
  src/backend/user-server/.gitignore
  src/backend/user-server/.prettierrc
  src/backend/user-server/Dockerfile
  src/backend/user-server/README.md
  src/backend/user-server/docker-compose.yml
  src/backend/user-server/eslint.config.mjs
  src/backend/user-server/nest-cli.json
  src/backend/user-server/package.json
  src/backend/user-server/pnpm-lock.yaml
  src/backend/user-server/src/app.module.ts
  src/backend/user-server/src/main.ts
  src/backend/user-server/src/user/dto/create-user.dto.ts
  src/backend/user-server/src/user/dto/update-user.dto.ts
  src/backend/user-server/src/user/entity/user.entity.ts
  src/backend/user-server/src/user/user.controller.ts
  src/backend/user-server/src/user/user.module.ts
  src/backend/user-server/src/user/user.service.ts
  src/backend/user-server/tsconfig.build.json
  src/backend/user-server/tsconfig.json
  src/docker-compose.yml
Labels: FEAT, 🕹️BE

#92 [FE] FEAT: FE UI 개발 #86
  src/frontend/index.html
  src/frontend/src/App.css
  src/frontend/src/assets/data/myRoomListTest.ts
  src/frontend/src/assets/data/notificationListTest.ts
  src/frontend/src/assets/img/DisableEye.svg
  src/frontend/src/assets/img/DisableEye_W.svg
  src/frontend/src/assets/img/ShareLink.svg
  src/frontend/src/assets/img/UsersLine_W.svg
  src/frontend/src/assets/img/Video.svg
  src/frontend/src/components/Modal/ModalPortal.tsx
  src/frontend/src/components/Modal/NotificationModal/NotificationCard/index.css.ts
  src/frontend/src/components/Modal/NotificationModal/NotificationCard/index.tsx
  src/frontend/src/components/Modal/NotificationModal/index.css.ts
  src/frontend/src/components/Modal/NotificationModal/index.tsx
  src/frontend/src/components/Modal/RoomCreateModal/index.css.tsx
  src/frontend/src/components/Modal/RoomCreateModal/index.tsx
  src/frontend/src/components/Modal/RoomDeleteModal/index.tsx
  src/frontend/src/components/Modal/index.css.tsx
  src/frontend/src/components/Modal/index.tsx
  src/frontend/src/components/MyRoomCard/index.css.ts
  src/frontend/src/components/MyRoomCard/index.tsx
  src/frontend/src/components/TopNavBar/index.css.ts
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/pages/MyRoomPage/index.css.ts
  src/frontend/src/pages/MyRoomPage/index.tsx
  src/frontend/src/pages/RegisterPage/index.tsx
  src/frontend/src/types/dto/MyRoom.dto.ts
  src/frontend/src/types/dto/Notification.dto.ts
  src/frontend/src/utils/dateUtils.ts
Labels: FEAT, 🖥️FE

#101 [INFRA] FEAT: Redis, Redis Insight 도커에 추가 #100
  .gitignore
  src/.env
  src/backend/auth-server/.dockerignore
  src/backend/redis/docker-compose.yml
  src/backend/user-server/.dockerignore
  src/docker-compose.yml
Labels: FEAT, 🕹️BE, infra

#74 [BE] FEAT: 시그널링 서버 MVP 구현
  src/backend/signaling-server/.gitattributes
  src/backend/signaling-server/.gitignore
  src/backend/signaling-server/Dockerfile
  src/backend/signaling-server/build.gradle
  src/backend/signaling-server/docker-compose.yml
  src/backend/signaling-server/gradle/wrapper/gradle-wrapper.jar
  src/backend/signaling-server/gradle/wrapper/gradle-wrapper.properties
  src/backend/signaling-server/gradlew
  src/backend/signaling-server/gradlew.bat
  src/backend/signaling-server/settings.gradle
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/SignalingServerApplication.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/config/KurentoConfig.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/config/WebSocketConfig.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/controller/SignalingController.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/event/WebSocketEventListener.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/model/Room.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/model/UserSession.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/service/RoomManager.java
  src/backend/signaling-server/src/main/java/com/kickzo/signaling/service/UserSessionManager.java
  src/backend/signaling-server/src/main/resources/application.properties
  src/backend/signaling-server/src/test/java/com/kickzo/signaling/SignalingServerApplicationTests.java
Labels: FEAT, FIX, REFACTOR, 🕹️BE

#115 [BE] FIX: create kafka topics #110
  src/backend/kafka/docker-compose.yml
Labels: FIX, 🕹️BE

#97 [FE] FEAT: 검색 바 UI #93
  src/frontend/src/App.tsx
  src/frontend/src/assets/data/searchListTest.ts
  src/frontend/src/assets/img/Cancel.svg
  src/frontend/src/assets/img/Search.svg
  src/frontend/src/components/LeftNavBar/index.css.ts
  src/frontend/src/components/MyRoomCard/index.css.ts
  src/frontend/src/components/MyRoomCard/index.tsx
  src/frontend/src/components/Search/SearchBar/index.css.ts
  src/frontend/src/components/Search/SearchBar/index.tsx
  src/frontend/src/components/Search/SearchBarList/index.css.ts
  src/frontend/src/components/Search/SearchBarList/index.tsx
  src/frontend/src/components/Search/SearchBarListItem/ChangeToHTML.tsx
  src/frontend/src/components/Search/SearchBarListItem/index.css.ts
  src/frontend/src/components/Search/SearchBarListItem/index.tsx
  src/frontend/src/components/TopNavBar/index.css.ts
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/hooks/useDebounceCallback.ts
  src/frontend/src/pages/SearchPage/index.tsx
Labels: FEAT, 🖥️FE

#120 [BE] FEAT: 시그널링 서버 의존성 추가 및 docker 통합 #106
  src/.env
  src/backend/signaling-server/build.gradle
  src/backend/signaling-server/docker-compose.yml
  src/docker-compose.yml
Labels: FEAT, 🕹️BE

#122 [BE] FEAT: chat-server에 kafka consumer, websocket 연결 로직 추가 #105
  src/backend/chat-server/build.gradle
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/PlaylistItem.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/PlaylistUpdateEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/RoleChangeEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/RoomData.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/RoomEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/KafkaConsumerService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/MessagingService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/PlaylistEventHandler.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/RoomEventHandler.java
Labels: FEAT, 🕹️BE

#129 [BE] FEAT: 메인 서버 docker에 올리는 작업 #124
  src/backend/main-server/main/Dockerfile
  src/backend/main-server/main/docker-compose.yml
  src/backend/main-server/main/src/main/resources/application-dev.properties
  src/backend/main-server/main/src/main/resources/application-docker.properties
  src/backend/main-server/main/src/main/resources/application.properties
  src/docker-compose.yml
Labels: FEAT, 🕹️BE

#125 [BE] FEAT: user 서버 API 추가 #118
  src/backend/auth-server/src/auth/auth.controller.ts
  src/backend/auth-server/src/auth/auth.service.ts
  src/backend/auth-server/src/auth/constants/constants.ts
  src/backend/auth-server/src/auth/constants/env-key.constant.ts
  src/backend/auth-server/src/auth/constants/redis-key.constant.ts
  src/backend/auth-server/src/auth/decorator/authorization.decorator.ts
  src/backend/auth-server/src/auth/dto/device-type.dto.ts
  src/backend/auth-server/src/auth/interface/token-payload.interface.ts
  src/backend/user-server/package.json
  src/backend/user-server/pnpm-lock.yaml
  src/backend/user-server/src/app.module.ts
  src/backend/user-server/src/user/constants/constants.ts
  src/backend/user-server/src/user/constants/env-key.constants.ts
  src/backend/user-server/src/user/constants/redis-key.constant.ts
  src/backend/user-server/src/user/decorators/nickname.decorator.ts
  src/backend/user-server/src/user/decorators/password.decorator.ts
  src/backend/user-server/src/user/dto/check-exists.dto.ts
  src/backend/user-server/src/user/dto/create-user.dto.ts
  src/backend/user-server/src/user/dto/update-user.dto.ts
  src/backend/user-server/src/user/entity/user.entity.ts
  src/backend/user-server/src/user/user.controller.ts
  src/backend/user-server/src/user/user.service.ts
  src/infra/kong/kong.yml
Labels: FEAT, 🕹️BE

#131 [iOS] FEAT: Playslit View 구현 #108
  src/iOS/KickTube/KickTube/Common/Base/BaseViewController.swift
  src/iOS/KickTube/KickTube/Common/Enum/NetworkError.swift
  src/iOS/KickTube/KickTube/Common/Extensions/String+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UICollectionView+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UIImage+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Extensions/UIView+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/YoutubeSearchEndPoint.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/NetworkManager.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Router/YoutubeRouter.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/DomainModel/YouTubeVideoDomainModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/HomeDataModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/YouTubeVideoResponse.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/YoutubeVideoViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/HomeReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/KickRoomReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/HomeVideoCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/PlayListCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/KickRoomMainScrollView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/PlayListCollectionViewCellViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/PlaylistView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/YoutubeSearchResultView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/CreateRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/HomeViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/KickRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/MyRoom/MyRoomDataModel.swift
  src/iOS/KickTube/KickTube/Features/MyRoom/Reactor/MyRoomReactor.swift
  src/iOS/KickTube/KickTube/Info.plist
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/chat.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/chat.imageset/chat.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/trash.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/trash.imageset/trash.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/voice.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/voice.imageset/voice.svg
Labels: FEAT, 📱iOS

#136 [BE] FEAT: Swagger 추가 및 api 콜 로직 추가
  .gitignore
  src/.idea/.gitignore
  src/backend/main-server/main/.dockerignore
  src/backend/main-server/main/build.gradle
  src/backend/main-server/main/src/main/java/com/kickzo/main/config/KafkaProducerConfig.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/config/SwaggerConfig.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/constants/ApiResponseConstants.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/event/NewUserJoinEvent.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/request/CreateRoomRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/request/RoomUpdateRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/PlaylistDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/RoomDetailsDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/RoomInfoDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/RoomResponseDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/UserListDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/exception/CustomErrorCode.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/exception/CustomErrorResponse.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/exception/CustomException.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/exception/GlobalExceptionHandler.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/PlaylistRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/UserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/KafkaProducerService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/MainPageService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomUserService.java
  src/backend/main-server/main/src/main/resources/application-dev.properties
  src/backend/main-server/main/src/main/resources/application-docker.properties
  src/backend/main-server/main/src/main/resources/application.properties
  src/infra/kong/kong.yml
Labels: FEAT, FIX, 🕹️BE

#119 [FE] FEAT: Profile Detail에 나의 프로필 수정 기능 추가 #116
  src/frontend/eslint.config.js
  src/frontend/src/assets/data/chatDataTest.ts
  src/frontend/src/assets/img/Edit.svg
  src/frontend/src/assets/img/Setting.svg
  src/frontend/src/components/IconButton/index.tsx
  src/frontend/src/components/Sidebar/Chat/ChatNickname.tsx
  src/frontend/src/components/Sidebar/MemberList/MemberListFooter/index.tsx
  src/frontend/src/components/Sidebar/MemberList/index.tsx
  src/frontend/src/components/Sidebar/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
  src/frontend/src/components/common/ProfileDetail/ButtonContainer/index.css.ts
  src/frontend/src/components/common/ProfileDetail/ButtonContainer/index.tsx
  src/frontend/src/components/common/ProfileDetail/EditButton/index.tsx
  src/frontend/src/components/common/ProfileDetail/ProfileContent/index.css.ts
  src/frontend/src/components/common/ProfileDetail/ProfileContent/index.tsx
  src/frontend/src/components/common/ProfileDetail/RightButtonContainer/index.tsx
  src/frontend/src/components/common/ProfileDetail/index.css.ts
  src/frontend/src/components/common/ProfileDetail/index.tsx
  src/frontend/src/types/enums/ProfileDetailType.ts
Labels: FEAT, 🖥️FE

#139 [FE] FEAT: Room page 화면 만들기 #135
  src/frontend/src/components/RoomDetail/index.css.ts
  src/frontend/src/components/RoomDetail/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
  src/frontend/src/pages/RoomPage/index.css.ts
  src/frontend/src/pages/RoomPage/index.tsx
Labels: FEAT, 🖥️FE

#144 [iOS] FEAT: VoiceChatListView 구현 #141
  src/iOS/KickTube/KickTube/Common/Components/RoundButton.swift
  src/iOS/KickTube/KickTube/Common/Extensions/Notification+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Utilities/UserDefaultsManager.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/KickRoomVoiceUserViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/VoiceChatUserStateViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/VoiceChatListReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/VoiceUserOverviewReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/VoiceChatUserListCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/KickRoomMainScrollView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/VoiceChatListView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/CreateRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/KickRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/VoiceUserOverviewViewController.swift
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/disableMic.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/disableMic.imageset/mic_off.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/headset_off.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/headset_off.imageset/headset_off.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/headset_on.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/headset_on.imageset/headset_on.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/mic_off.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/mic_off.imageset/mic_off.svg
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/mic_on.imageset/Contents.json
  src/iOS/KickTube/KickTube/Resource/Assets.xcassets/icon/mic_on.imageset/mic_on.svg
Labels: FEAT, 📱iOS

#156 [FE] FEAT: 룸 API 적용 #147
  src/backend/main-server/main/build.gradle
  src/backend/main-server/main/src/main/java/com/kickzo/main/config/RedisConfig.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/InvitationController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/request/RoleChangeRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/request/RoomInviteRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/request/RoomJoinRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/InvitationService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomUserService.java
  src/backend/main-server/main/src/main/resources/application-dev.properties
  src/backend/main-server/main/src/main/resources/application-docker.properties
  src/backend/user-server/src/user/user.controller.ts
  src/backend/user-server/src/user/user.service.ts
  src/frontend/src/App.css
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/api/endpoints/room/room.interface.ts
  src/frontend/src/api/endpoints/user/user.api.ts
  src/frontend/src/assets/img/DefaultThumbnail.svg
  src/frontend/src/components/LeftNavBar/index.tsx
  src/frontend/src/components/Modal/RoomCreateModal/index.css.tsx
  src/frontend/src/components/Modal/RoomCreateModal/index.tsx
  src/frontend/src/components/MyRoomCard/index.css.ts
  src/frontend/src/components/MyRoomCard/index.tsx
  src/frontend/src/components/VideoCard/index.css.ts
  src/frontend/src/components/VideoCard/index.tsx
  src/frontend/src/hooks/queries/useCreateRoom.ts
  src/frontend/src/hooks/queries/useMyRooms.ts
  src/frontend/src/hooks/queries/useRooms.ts
  src/frontend/src/hooks/utils/useDelayedLoading.ts
  src/frontend/src/pages/HomePage/HomeSkeleton/index.css.ts
  src/frontend/src/pages/HomePage/HomeSkeleton/index.tsx
  src/frontend/src/pages/HomePage/index.tsx
  src/frontend/src/pages/MyRoomPage/MyRoomSkeleton/index.css.ts
  src/frontend/src/pages/MyRoomPage/MyRoomSkeleton/index.tsx
  src/frontend/src/pages/MyRoomPage/index.tsx
  src/frontend/src/types/dto/MyRoom.dto.ts
  src/frontend/src/utils/stringUtils.ts
  src/infra/kong/kong.yml
Labels: FEAT, 🖥️FE

#150 [FE] FEAT: 웹소켓 연결, 채팅 구현 및 리팩토링 #123
  src/frontend/package.json
  src/frontend/pnpm-lock.yaml
  src/frontend/src/components/Sidebar/Chating/ChatInput/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatInput/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/ChatNickname/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/ChatNickname/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatMessages/index.tsx
  src/frontend/src/components/Sidebar/Chating/index.css.ts
  src/frontend/src/components/Sidebar/Chating/index.tsx
  src/frontend/src/components/Sidebar/index.tsx
  src/frontend/src/components/common/Input/index.tsx
  src/frontend/src/stores/useChatStore.ts
  src/frontend/vite.config.ts
Labels: FEAT, 🖥️FE

#152 [FE] FIX: ProfileDetail과 MyProfile 분리
  src/frontend/src/components/Profile/MyProfile/index.css.ts
  src/frontend/src/components/Profile/MyProfile/index.tsx
  src/frontend/src/components/Sidebar/MemberList/index.tsx
  src/frontend/src/components/common/ProfileDetail/ButtonContainer/index.css.ts
  src/frontend/src/components/common/ProfileDetail/ButtonContainer/index.tsx
  src/frontend/src/components/common/ProfileDetail/EditButton/index.tsx
  src/frontend/src/components/common/ProfileDetail/ProfileActions/index.tsx
  src/frontend/src/components/common/ProfileDetail/ProfileContent/index.css.ts
  src/frontend/src/components/common/ProfileDetail/ProfileContent/index.tsx
  src/frontend/src/components/common/ProfileDetail/ProfileHeader/index.tsx
  src/frontend/src/components/common/ProfileDetail/ProfileInfo/index.tsx
  src/frontend/src/components/common/ProfileDetail/RightButtonContainer/index.tsx
  src/frontend/src/components/common/ProfileDetail/index.tsx
  src/frontend/src/types/dto/ProfileDetailDto.dto.ts
Labels: FEAT, 🖥️FE

#145 [BE] FEAT: chat-server에 userlist 받는 consumer 추가 #137
  .gitignore
  src/backend/chat-server/Dockerfile
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/config/KafkaConsumerConfig.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/NewUserJoinEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/UserListDto.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/KafkaConsumerService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/RoomEventHandler.java
Labels: FEAT, FIX, 🕹️BE

#162 [BE] FEAT: 메인 서버 - 초대 기능 추가 및 API endpoint 수정
  src/backend/main-server/main/src/main/java/com/kickzo/main/config/RedisConfig.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/InvitationController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/MainPageController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/data/InvitationData.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/data/PlaylistItem.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/event/PlaylistUpdateEvent.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/request/RoomPlaylistRequestDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/RoomDetailsDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/Playlist.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/enums/InvitationStatus.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/exception/CustomErrorCode.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomUserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/UserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/InvitationService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/KafkaProducerService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/MainPageService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/PlaylistService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
Labels: FEAT, FIX, REFACTOR, 🕹️BE

#170 [iOS] BUG: 유저 목록 bottom sheet 문제 해결 #169
  src/iOS/KickTube/KickTube/Features/Home/Reactor/UserListReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/UserListView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/VoiceChatListView.swift
Labels: BUG, 📱iOS

#160 [FE] FIX: 드래그앤드롭 미리보기 추가 및 플레이리스트 형태 맞추기 #157
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.css.ts
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.tsx
  src/frontend/src/components/Sidebar/Playlist/index.css.ts
  src/frontend/src/components/Sidebar/Playlist/index.tsx
  src/frontend/src/hooks/utils/useDebounce.ts
  src/frontend/src/stores/useVideoStore.ts
Labels: FEAT, 🖥️FE

#165 [BE] FIX: 새로운 유저 입장 시 Kafka produce 하는 방식 변경 #164
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomApi.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/controller/RoomController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/event/NewUserJoinEvent.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/RoomDetailsDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/UserInfoDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/KafkaProducerService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
Labels: FIX, 🕹️BE

#173 [BE] FIX: 채팅 서버 - Kafka consumer 수정 (user-join, playlist-update) #166
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/NewUserJoinEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/UserInfoDto.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/KafkaConsumerService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/MessagingService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/PlaylistEventHandler.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/RoomEventHandler.java
Labels: FIX, 🕹️BE

#175 [FE] 상단 네비게이션 바- 프로필 UI 및 기능 추가 #158
  src/frontend/src/api/endpoints/user/user.interface.ts
  src/frontend/src/assets/img/CancelSmall.svg
  src/frontend/src/assets/img/Edit.svg
  src/frontend/src/components/IconButton/index.css.ts
  src/frontend/src/components/IconButton/index.tsx
  src/frontend/src/components/Modal/NotificationModal/index.css.ts
  src/frontend/src/components/Modal/NotificationModal/index.tsx
  src/frontend/src/components/Modal/ProfileModal/index.tsx
  src/frontend/src/components/Modal/index.css.tsx
  src/frontend/src/components/Profile/MyProfile/index.css.ts
  src/frontend/src/components/Profile/MyProfile/index.tsx
  src/frontend/src/components/TopNavBar/index.css.ts
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/components/VideoCard/index.tsx
  src/frontend/src/components/common/Button/index.css.ts
  src/frontend/src/stores/useUserStore.ts
  src/frontend/src/utils/colorUtils.ts
Labels: FEAT, 🖥️FE

#154 [BE] FEAT: feat friend server & docker #153
  src/.env
  src/backend/friend-server/Dockerfile
  src/backend/friend-server/__pycache__/friend.cpython-310.pyc
  src/backend/friend-server/docker-compose.yml
  src/backend/friend-server/friend.py
  src/backend/friend-server/requirements.txt
  src/docker-compose.yml
Labels: FEAT, 🕹️BE

#184 [BE] FIX: friend server, api 수정 #182
  src/backend/friend-server/friend.py
  src/infra/kong/kong.yml
Labels: FIX, 🕹️BE

#188 [iOS] REFACTOR: 네트워크 레이어 재설계 #179
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Base/BaseViewController.swift
  src/iOS/KickTube/KickTube/Common/Extensions/HTTPURLResponse+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Utilities/KeyChain/KeyChainManager.swift
  src/iOS/KickTube/KickTube/Common/Utilities/KeyChain/KeyChainValue.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Enum/HTTPMethod.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Enum/HTTPStatusCode.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Enum/HeaderContent.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Enum/NetworkError.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Enum/ResponsePipeline.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/JSONParsePipeline.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/RefreshTokenRedirector.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/Session.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/Request.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/ResponsePipelineRedirector.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/ResponsePipelineTerminator.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/RequestImplement/DefaultRequest.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/RequestImplement/LoginRequest.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/CreateRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginDataModel.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginReactor.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginViewController.swift
Labels: REFACTOR, 📱iOS

#185 [BE] auth, user 서버 swagger 추가 및 버저닝 적용 #183
  src/backend/auth-server/nest-cli.json
  src/backend/auth-server/package.json
  src/backend/auth-server/pnpm-lock.yaml
  src/backend/auth-server/src/auth/auth.controller.ts
  src/backend/auth-server/src/auth/dto/device-type.dto.ts
  src/backend/auth-server/src/main.ts
  src/backend/user-server/nest-cli.json
  src/backend/user-server/package.json
  src/backend/user-server/pnpm-lock.yaml
  src/backend/user-server/src/main.ts
  src/backend/user-server/src/user/dto/check-exists.dto.ts
  src/backend/user-server/src/user/dto/create-user.dto.ts
  src/backend/user-server/src/user/dto/update-user.dto.ts
  src/backend/user-server/src/user/entity/user.entity.ts
  src/backend/user-server/src/user/user.controller.ts
Labels: FEAT, 🕹️BE

#171 [FE] FEAT: 유저리스트 정렬 관리 #161
  src/frontend/src/components/Sidebar/MemberList/index.tsx
  src/frontend/src/components/Sidebar/UserList/UserListFooter/index.tsx
  src/frontend/src/components/Sidebar/UserList/index.css.ts
  src/frontend/src/components/Sidebar/UserList/index.tsx
  src/frontend/src/components/Sidebar/VoiceChat/index.css.ts
  src/frontend/src/components/Sidebar/VoiceChat/index.tsx
  src/frontend/src/components/Sidebar/index.tsx
  src/frontend/src/hooks/utils/RedBlackTree.ts
  src/frontend/src/types/enums/ProfileDetailType.ts
  src/frontend/src/types/enums/SidebarType.ts
Labels: FEAT, 🖥️FE

#186 [FE] FEAT: chatData 이중연결리스트 적용 및 개선
  src/frontend/src/components/Sidebar/Chating/index.tsx
  src/frontend/src/hooks/utils/DoublyLinkedList.ts
Labels: FEAT, 🖥️FE

#181 [BE] FEAT: 채팅 서버 - WebSocket 붙이기 #174
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/config/JacksonConfig.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/config/KafkaConsumerConfig.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/controller/RoomController.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/controller/WebSocketController.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/RoomEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/playlist/PlayTime.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/playlist/PlaylistItem.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/playlist/PlaylistUpdateEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/ChatMessage.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/NewUserJoinEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/RoleChangeEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/RoomData.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/UserInfoDto.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/user/ConnectionEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/user/FriendNotification.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/user/InvitationData.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/user/UserStatusEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/enums/EventType.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/event/WebSocketEventListener.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/repository/KafkaRepository.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/KafkaConsumerService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/MessagingService.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/PlaylistEventHandler.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/RoomEventHandler.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/RoomManager.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/WebSocketRoomService.java
  src/backend/chat-server/src/main/resources/static/index.html
Labels: FEAT, FIX, 🕹️BE

#187 [FE] FEAT: 메인에 소켓 연결 #178
  src/frontend/src/App.tsx
  src/frontend/src/api/endpoints/auth/auth.api.ts
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/api/endpoints/room/room.interface.ts
  src/frontend/src/components/RoomDetail/index.css.ts
  src/frontend/src/components/RoomDetail/index.tsx
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/hooks/queries/useCurrentRoom.ts
  src/frontend/src/hooks/queries/useMyRooms.ts
  src/frontend/src/main.tsx
  src/frontend/src/pages/MyRoomPage/MyRoomSkeleton/index.tsx
  src/frontend/src/pages/MyRoomPage/index.css.ts
  src/frontend/src/pages/MyRoomPage/index.tsx
  src/frontend/src/pages/NotFoundPage/index.css.ts
  src/frontend/src/pages/NotFoundPage/index.tsx
  src/frontend/src/pages/RoomPage/index.tsx
  src/frontend/src/pages/SettingPage/index.tsx
  src/frontend/src/stores/useChatStore.ts
  src/frontend/src/stores/useCurrentRoomStore.ts
  src/frontend/src/stores/useMyRoomsStore.ts
  src/frontend/src/stores/useUserStore.ts
  src/frontend/src/stores/useWebSocketStore.ts
  src/frontend/src/types/dto/Message.dto.ts
  src/frontend/src/ui/Common.css.ts
  src/infra/stomp-tester/stomp-tester.html
Labels: FEAT, 🖥️FE

#200 [FE] FEAT: 채팅 소켓 연결 #193
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/api/endpoints/room/room.interface.ts
  src/frontend/src/components/Modal/RoomCreateModal/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/ChatNickname/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatMessages/index.tsx
  src/frontend/src/components/Sidebar/Chating/index.css.ts
  src/frontend/src/components/Sidebar/Chating/index.tsx
  src/frontend/src/components/Sidebar/index.tsx
  src/frontend/src/pages/RoomPage/index.tsx
  src/frontend/src/stores/useCurrentRoomStore.ts
  src/frontend/src/stores/useMyRoomsStore.ts
  src/frontend/src/stores/useWebSocketStore.ts
  src/frontend/src/types/dto/Message.dto.ts
  src/frontend/src/utils/dateUtils.ts
Labels: FEAT, 🖥️FE

#211 [iOS] TEST: 네트워크 테스트
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/Session.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/URLSessionProtocol.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/HomeRoomResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/ChatReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/VoiceChatListReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/VoiceUserOverviewReactor.swift
  src/iOS/KickTube/KickTube/KickTubeTests/KickTubeTests.swift
  src/iOS/KickTube/KickTube/KickTubeTests/MockRequest.swift
  src/iOS/KickTube/KickTube/KickTubeTests/MockSession.swift
Labels: FEAT, TEST, 📱iOS

#217 [iOS] BUG: git branch 병합 오류 수정 및 화면 뒤로가기 기능 추가
  src/iOS/.vscode/settings.json
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Features/Home/Reactor/ChatReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/VoiceChatListReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/VoiceUserOverviewReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/HomeViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/KickRoomViewController.swift
  src/iOS/ManipulateDataModel/.gitignore
  src/iOS/ManipulateDataModel/.swiftpm/xcode/xcuserdata/sk.xcuserdatad/xcschemes/xcschememanagement.plist
  src/iOS/ManipulateDataModel/Package.resolved
  src/iOS/ManipulateDataModel/Package.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModel/ManipulateDataModel.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelClient/main.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/DTOMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/DataModelMappingMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/KeyMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/ManipulateDataModelMacro.swift
  src/iOS/ManipulateDataModel/Sources/ManipulateDataModelMacros/ManipulateDataModelPlugin.swift
  src/iOS/ManipulateDataModel/Tests/ManipulateDataModelTests/ManipulateDataModelTests.swift
Labels: BUG

#218 [iOS] TEST: 의존성 주입 및 네트워크 테스트
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Implement/Session.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Network/Protocol/URLSessionProtocol.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/HomeRoomResponseDTO.swift
  src/iOS/KickTube/KickTube/KickTubeTests/KickTubeTests.swift
  src/iOS/KickTube/KickTube/KickTubeTests/MockRequest.swift
  src/iOS/KickTube/KickTube/KickTubeTests/MockSession.swift
Labels: FEAT, TEST, 📱iOS

#226 [iOS] FEAT: Chatting Data를 Local DB에 저장 #219
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Utilities/DataBase/ChatDataRepository.swift
  src/iOS/KickTube/KickTube/Common/Utilities/DataBase/ChatMessageEntity.swift
  src/iOS/KickTube/KickTube/Common/Utilities/DataBase/ChatRoomEntity.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/DomainModel/ChatMessageDomainModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/DomainModel/KickRoomDomainModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/ChatMessageViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/HomeRoomViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/KickRoomViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/ChatReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/HomeReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/ChatCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/ChatMessageSection.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/HomeVideoCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/UserListCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/ChatViewController.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/HomeViewController.swift
Labels: FEAT, 📱iOS

#210 [BE] FIX: 검색 기능 추가 및 기타 수정사항 반영 #205
  src/backend/chat-server/build.gradle
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/controller/WebSocketController.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/playlist/PlayTime.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/ChatMessage.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/WebSocketRoomService.java
  src/backend/chat-server/src/main/resources/logback.xml
  src/backend/chat-server/src/main/resources/static/index.html
  src/backend/elk/cleanup.sh
  src/backend/elk/docker-compose-es.yml
  src/backend/elk/docker-compose-kibana.yml
  src/backend/elk/elasticsearch-init.sh
  src/backend/main-server/main/docker-compose.yml
  src/backend/main-server/main/kibana.yml
  src/backend/main-server/main/src/main/java/com/kickzo/main/MainApplication.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/RoomSearchController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/RoomResponseDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/entity/User.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/RoomRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/UserRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/controller/SearchController.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/document/RoomDocument.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/document/UserDocument.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/repository/RoomSearchRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/repository/UserSearchRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/service/SearchService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/service/UserBatchService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/search/service/UserRowMapper.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/MainPageService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
  src/docker-compose.yml
Labels: FEAT, FIX, 🕹️BE

#222 [FE] FEAT: 유튜브 영상, 플레이리스트, 유저리스트 웹소켓 연결
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/components/RoleChangeButton/index.tsx
  src/frontend/src/components/Sidebar/Playlist/index.tsx
  src/frontend/src/components/Sidebar/UserList/index.tsx
  src/frontend/src/components/Sidebar/VoiceChat/index.tsx
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
  src/frontend/src/components/common/ProfileDetail/ProfileActions/index.tsx
  src/frontend/src/components/common/ProfileDetail/index.tsx
  src/frontend/src/pages/RoomPage/index.tsx
  src/frontend/src/stores/useCurrentRoomStore.ts
  src/frontend/src/stores/useUserStore.ts
  src/frontend/src/stores/useVideoStore.ts
  src/frontend/src/stores/useWebSocketStore.ts
  src/frontend/src/types/dto/ProfileDetailDto.dto.ts
  src/frontend/src/utils/playlistUtils.ts
Labels: FEAT, 🖥️FE

#232 [FE] FEAT: Sentry 도입 #228
  src/frontend/.env.sample
  src/frontend/README.md
  src/frontend/package.json
  src/frontend/pnpm-lock.yaml
  src/frontend/src/api/axios.instance.ts
  src/frontend/src/api/axios.log.ts
  src/frontend/src/api/endpoints/auth/auth.api.ts
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/api/endpoints/user/user.api.ts
  src/frontend/src/main.tsx
  src/frontend/src/sentry.ts
  src/frontend/src/stores/useUserStore.ts
  src/frontend/src/types/enums/ErrorType.ts
  src/frontend/vite.config.ts
  src/infra/kong/kong.yml
Labels: FEAT, 🖥️FE

#234 [FE] FEAT: 반응형 thumbnail 추가 #233
  src/frontend/src/components/MyRoomCard/index.css.ts
  src/frontend/src/components/MyRoomCard/index.tsx
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.css.ts
  src/frontend/src/components/VideoCard/index.css.ts
  src/frontend/src/components/VideoCard/index.tsx
  src/frontend/src/utils/youtubeUtils.ts
Labels: FEAT, 🖥️FE

#235 [COMMON] FEAT: 프로필 이미지 S3 업로드 #229
  src/backend/user-server/src/user/dto/profile-image.dto.ts
  src/backend/user-server/src/user/user.controller.ts
  src/backend/user-server/src/user/user.service.ts
  src/frontend/src/api/endpoints/file/file.api.ts
  src/frontend/src/api/endpoints/user/user.api.ts
  src/frontend/src/components/Profile/MyProfile/index.css.ts
  src/frontend/src/components/Profile/MyProfile/index.tsx
  src/frontend/src/stores/useUserStore.ts
  src/frontend/src/utils/uploadFile.ts
Labels: FEAT, 🖥️FE

#244 [BE] FEAT: 메인 서버 - 방 마다 실시간 접속자 관리 #237
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/controller/WebSocketController.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/UserInfoDto.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/dto/room/UserOutEvent.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/repository/KafkaRepository.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/RoomEventHandler.java
  src/backend/chat-server/src/main/java/kickzo/stomp_chat/service/WebSocketRoomService.java
  src/backend/chat-server/src/main/resources/static/index.html
  src/backend/main-server/main/src/main/java/com/kickzo/main/config/KafkaConsumerConfig.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/config/RedisConfig.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/event/UserOutEvent.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/dto/response/UserInfoDto.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/exception/CustomErrorCode.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/UserEnterRedisRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/repository/UserOutRedisRepository.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/KafkaConsumerService.java
  src/backend/main-server/main/src/main/java/com/kickzo/main/service/RoomService.java
  src/backend/main-server/main/src/main/resources/application-dev.properties
  src/backend/main-server/main/src/main/resources/application-docker.properties
  src/backend/main-server/main/src/main/resources/application.properties
Labels: FEAT, 🕹️BE

#246 [FE] FEAT: bug 및 UI 수정, 검색 수정 #243
  src/backend/main-server/main/docker-compose.yml
  src/frontend/src/App.tsx
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/api/endpoints/room/room.interface.ts
  src/frontend/src/assets/data/memberListTest.ts
  src/frontend/src/assets/img/Key.svg
  src/frontend/src/components/Modal/MyProfileModal/index.tsx
  src/frontend/src/components/Modal/ProfileModal/index.tsx
  src/frontend/src/components/Modal/RoomProfileModal/index.tsx
  src/frontend/src/components/MyRoomCard/index.css.ts
  src/frontend/src/components/MyRoomCard/index.tsx
  src/frontend/src/components/RoomDetail/index.css.ts
  src/frontend/src/components/Search/SearchBar/index.tsx
  src/frontend/src/components/Search/SearchBarList/index.tsx
  src/frontend/src/components/Search/SearchBarListItem/index.css.ts
  src/frontend/src/components/Search/SearchBarListItem/index.tsx
  src/frontend/src/components/Search/SearchItem/SearchRoomItem/index.tsx
  src/frontend/src/components/Search/SearchItem/SearchUserItem/index.css.ts
  src/frontend/src/components/Search/SearchItem/SearchUserItem/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatInput/index.css.ts
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/ChatNickname/index.tsx
  src/frontend/src/components/Sidebar/Chating/ChatMessages/ChatLayout/index.css.ts
  src/frontend/src/components/Sidebar/Chating/index.css.ts
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.css.ts
  src/frontend/src/components/Sidebar/Playlist/index.css.ts
  src/frontend/src/components/Sidebar/UserList/UserListFooter/index.tsx
  src/frontend/src/components/Sidebar/UserList/index.css.ts
  src/frontend/src/components/Sidebar/UserList/index.tsx
  src/frontend/src/components/Sidebar/VoiceChat/index.css.ts
  src/frontend/src/components/Sidebar/VoiceChat/index.tsx
  src/frontend/src/components/Sidebar/index.css.ts
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
  src/frontend/src/components/common/Input/index.css.ts
  src/frontend/src/components/common/ProfileDetail/ProfileInfo/index.tsx
  src/frontend/src/components/common/ProfileDetail/index.css.ts
  src/frontend/src/components/common/ProfileDetail/index.tsx
  src/frontend/src/components/common/RoleNickname/index.css.ts
  src/frontend/src/components/common/RoleNickname/index.tsx
  src/frontend/src/components/common/SmallProfile/index.css.ts
  src/frontend/src/components/common/SmallProfile/index.tsx
  src/frontend/src/pages/Layout/index.css.ts
  src/frontend/src/pages/MyRoomPage/MyRoomSkeleton/index.css.ts
  src/frontend/src/pages/RegisterPage/index.tsx
  src/frontend/src/pages/RoomPage/index.css.ts
  src/frontend/src/pages/SearchPage/index.tsx
  src/frontend/src/types/enums/UserRole.ts
  src/frontend/src/ui/Common.css.ts
Labels: FEAT, 🖥️FE

#236 [iOS] FEAT: Socket 연결 #212
  src/iOS/KickTube/KickTube.xcodeproj/project.pbxproj
  src/iOS/KickTube/KickTube/Common/Extensions/Dictionary+Extensions.swift
  src/iOS/KickTube/KickTube/Common/Utilities/DataBase/ChatMessageEntity.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Socket/Enum/WebSocketTopic.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Socket/Implemenet/WebSocketURL.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Socket/Protocol/WebSocketEndPointConfigurable.swift
  src/iOS/KickTube/KickTube/Common/Utilities/Socket/WebSocketService.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/DomainModel/KickRoomChangeUserRoleDomainModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/ChatMessageResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/KickRoomChangeUserRoleResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/KickRoomNewUserResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/KickRoomPlayStateResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/KickRoomPlaylistChangeResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/Response/KickRoomResponseDTO.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/KickRoomChangeUserRoleViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/KickRoomPlayerStateViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/DataModel/ViewModel/VoiceChatUserStateViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/ChatReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/KickRoomReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/PlayListViewModel.swift
  src/iOS/KickTube/KickTube/Features/Home/Reactor/UserListReactor.swift
  src/iOS/KickTube/KickTube/Features/Home/View/Cell/PlayListCollectionViewCell.swift
  src/iOS/KickTube/KickTube/Features/Home/View/View/UserListView.swift
  src/iOS/KickTube/KickTube/Features/Home/View/ViewController/KickRoomViewController.swift
  src/iOS/KickTube/KickTube/Features/Login/LoginReactor.swift
  src/iOS/KickTube/Podfile
  src/iOS/KickTube/Podfile.lock
Labels: FEAT, BUG, 📱iOS

#247 [FE] BUG: 페이지 바꿀때 재생 영상 남아있는 문제 해결
  src/frontend/src/components/Sidebar/Playlist/PlaylistItem/index.tsx
  src/frontend/src/components/Sidebar/Playlist/index.tsx
  src/frontend/src/components/TopNavBar/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
  src/frontend/src/pages/RoomPage/index.tsx
  src/frontend/src/stores/useVideoStore.ts
Labels: BUG, 🖥️FE

#254 [FE] FIX: 버그 수정 #253
  src/backend/auth-server/src/auth/constants/constants.ts
  src/frontend/src/App.tsx
  src/frontend/src/api/endpoints/room/room.api.ts
  src/frontend/src/components/LeftNavBar/index.css.ts
  src/frontend/src/components/LeftNavBar/index.tsx
  src/frontend/src/components/Modal/RegisterSuccessModal/index.tsx
  src/frontend/src/components/RoomDetail/index.tsx
  src/frontend/src/components/Sidebar/Chating/index.tsx
  src/frontend/src/pages/MyRoomPage/index.tsx
  src/frontend/src/pages/RoomPage/index.tsx
  src/frontend/src/sentry.ts
  src/frontend/src/stores/useAuthStore.ts
  src/frontend/src/stores/useMyRoomsStore.ts
  src/frontend/src/stores/useWebSocketStore.ts
  src/frontend/src/types/window.d.ts
  src/frontend/src/ui/Common.css.ts
Labels: FEAT, 🖥️FE

#257 [FE] FIX: myRole, roomId 받아오는 방법 변경 #256
  src/frontend/src/components/Sidebar/UserList/index.tsx
  src/frontend/src/components/Sidebar/VoiceChat/index.tsx
  src/frontend/src/components/YoutubePlayer/index.tsx
Labels: FIX, 🖥️FE

#255 [BE] FEAT: 시그널링 Express 구현 #252
  src/backend/signaling-express-server/.env.dev
  src/backend/signaling-express-server/.env.docker
  src/backend/signaling-express-server/Dockerfile
  src/backend/signaling-express-server/docker-compose.yml
  src/backend/signaling-express-server/package-lock.json
  src/backend/signaling-express-server/package.json
  src/backend/signaling-express-server/server.js
  src/docker-compose.yml
  src/infra/kong/kong.yml
Labels: FEAT, 🕹️BE

#251 [COMMON] DOCS: README 초안 작성 #250
  README.md
Labels: DOCS

#259 [FE] FEAT: 음성채팅 구현 #258
  src/frontend/package.json
  src/frontend/pnpm-lock.yaml
  src/frontend/src/components/Sidebar/VoiceChat/index.css.ts
  src/frontend/src/components/Sidebar/VoiceChat/index.tsx
Labels: FEAT, 🖥️FE
